name: "Release"
description: "Release a new version of the library"

inputs:
  tag:
    description: "Tag to release"
    required: true
  npm-token:
    description: "Token to authenticate with npm"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check that was not published on npm
      working-directory: lib
      run: |
        VERSION=$(echo "${{ inputs.tag }}" | sed 's/^v//')
        PACKAGE_NAME=$(jq -r .name package.json)
        if ! npm view "$PACKAGE_NAME@$VERSION" > /dev/null 2>&1; then
          echo "✅ Version $VERSION is not published on npm."
        else
          echo "❌ ERROR: Version $VERSION already exists on npm! Please use a different version."
          exit 1
        fi
      shell: bash

    - name: Check npm publishing (dry run)
      working-directory: lib
      run: npm publish --dry-run
      shell: bash

    - name: Create a new release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.tag }}
        make_latest: true
        generate_release_notes: true

    - name: Authenticate with npm
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ~/.npmrc
      shell: bash

    - name: Publish package on npm
      working-directory: lib
      run: npm publish
      shell: bash
