name: "Deploy demo"
description: "Deploy the demo app to GitHub Pages"

inputs:
  keep-files:
    description: "Keep existing files in the gh-pages branch"
    required: false
    type: "boolean"
    default: false
  branch:
    description: "Branch to deploy to"
    required: false
    default: "gh-pages"
  token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.token }}
        publish_dir: demo/dist
        publish_branch: ${{ inputs.branch }}
        allow_empty_commit: true
        enable_jekyll: false
        keep_files: ${{ inputs.keep_files }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
