name: Deploy demo

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy to"
        required: false
        default: "gh-pages"
      keep-files:
        description: "Keep existing files in the target branch"
        required: false
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy demo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        uses: ./.github/actions/build
        with:
          base-path: /lightweight-charts-react-components

      - name: Deploy
        uses: ./.github/actions/deploy-examples
        with:
          keep-files: ${{ github.event.inputs.keep-files }}
          branch: ${{ github.event.inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
